name: deploy

on:
  push:
    branches:
      - master

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v3
      
      - name: Get github action IP
        id: ip
        uses: haythem/public-ip@v1.3
        
      - name: Set env
        run: |
          echo "AWS_DEFAULT_REGION=ap-northeast-2" >> $GITHUB_ENV 
          echo "AWS_SG_NAME=dizzyfox734" >> $GITHUB_ENV
          
      - name: Add Github Actions IP in Security Groups
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32      
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: ${{ env. AWS_DEFAULT_REGION }}
          
      - name: Run build in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app/docker_empty
            sh deploy.sh
      - name: Remove Github Actions IP in Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }} 
        if : always()
